from django.core.management.base import BaseCommand
from game.models import GameObject
from decimal import Decimal


class Command(BaseCommand):
    help = 'Initialize starter objects for the game'

    def handle(self, *args, **kwargs):
        starter_objects = [
            # Hunter-Gatherer starters (already exist)
            {
    'object_name': 'Rock',
    'era_name': 'Hunter-Gatherer',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('10'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'A simple rock. Hard and useful.',
    'image_path': '/media/objects/starter-rock.png'
    },
    {
    'object_name': 'Stick',
    'era_name': 'Hunter-Gatherer',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('10'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'A sturdy stick. Nature\'s first tool.',
    'image_path': '/media/objects/starter-stick.png'
    },
    {
    'object_name': 'Water',
    'era_name': 'Hunter-Gatherer',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('10'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'Pure water. Essential for life.',
    'image_path': '/media/objects/starter-water.png'
    },
    {
    'object_name': 'Dry Grass',
    'era_name': 'Hunter-Gatherer',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('10'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'Tinder that whispers of fire.',
    'image_path': '/media/objects/starter-drygrass.png'
    },
    # Agriculture starters
    {
    'object_name': 'Seed',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('100'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.3'),
    'global_modifiers': [],
    'flavor_text': 'A tiny start to a larger plan.',
    'image_path': '/media/objects/starter-seed.png'
    },
    {
    'object_name': 'Clay',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('100'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'Moldable earth, patient and steadfast.',
    'image_path': '/media/objects/starter-clay.png'
    },
    {
    'object_name': 'Wood',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('100'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.7'),
    'global_modifiers': [],
    'flavor_text': 'Straight grain, ready for work and fire.',
    'image_path': '/media/objects/starter-wood.png'
    },
    {
    'object_name': 'Fiber',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('100'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Plant strands for rope, cloth, and binding.',
    'image_path': '/media/objects/starter-fiber.png'
    },
    {
    'object_name': 'Village Notice Board',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'cultural',
    'quality_tier': 'uncommon',
    'cost': Decimal('1600'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('18'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 60,
    'operation_duration_sec': 3600,
    'retire_payout_coins_pct': Decimal('0.25'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.0'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['farm', 'natural'],
            'affected_tags': [],
            'income_multiplier': 1.06,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.06,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Announcements keep the village humming and fields coordinated.',
    'image_path': '/media/objects/starter-noticeboard.png'
    },
    {
    'object_name': 'Storehouse Ledger',
    'era_name': 'Agriculture',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('1800'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('22'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 75,
    'operation_duration_sec': 4000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.0'),
    'global_modifiers': [
        {
            'active_when': 'placed',
            'affected_categories': ['farm'],
            'affected_tags': [],
            'income_multiplier': 1.05,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 0.97,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Tidy grain counts shave hours off planting and harvest prep.',
    'image_path': '/media/objects/starter-ledger.png'
    },
    # Metallurgy starters
    {
    'object_name': 'Ore',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('1000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.6'),
    'global_modifiers': [],
    'flavor_text': 'Stone veined with promise.',
    'image_path': '/media/objects/starter-ore.png'
    },
    {
    'object_name': 'Charcoal',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('1000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'Hot, clean fuel for the first furnaces.',
    'image_path': '/media/objects/starter-charcoal.png'
    },
    {
    'object_name': 'Clay Crucible',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'factory',
    'quality_tier': 'common',
    'cost': Decimal('1000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.6'),
    'global_modifiers': [],
    'flavor_text': 'A small pot that endures great heat.',
    'image_path': '/media/objects/starter-crucible.png'
    },
    {
    'object_name': 'Bellows',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'common',
    'cost': Decimal('1000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.7'),
    'global_modifiers': [],
    'flavor_text': 'Leather lungs that breathe fire hotter.',
    'image_path': '/media/objects/starter-bellows.png'
    },
    {
    'object_name': 'Foundry Banner',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'cultural',
    'quality_tier': 'uncommon',
    'cost': Decimal('12000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('120'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 90,
    'operation_duration_sec': 5400,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.2'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['mine', 'factory'],
            'affected_tags': [],
            'income_multiplier': 1.08,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Raised above the forge, it keeps every crew pulling together.',
    'image_path': '/media/objects/starter-foundrybanner.png'
    },
    {
    'object_name': 'Forge Bell',
    'era_name': 'Metallurgy',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('14000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('130'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 110,
    'operation_duration_sec': 5600,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.2'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['factory'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 0.95,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'A resonant cue that trims downtime across the workshop floor.',
    'image_path': '/media/objects/starter-forgebell.png'
    },
    # Steam & Industry starters
    {
    'object_name': 'Iron',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('10000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.7'),
    'global_modifiers': [],
    'flavor_text': 'Refined metal ready for machines.',
    'image_path': '/media/objects/starter-iron.png'
    },
    {
    'object_name': 'Steam',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'common',
    'cost': Decimal('10000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.8'),
    'global_modifiers': [],
    'flavor_text': 'Boiling breath that turns wheels.',
    'image_path': '/media/objects/starter-steam.png'
    },
    {
    'object_name': 'Gear',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'factory',
    'quality_tier': 'common',
    'cost': Decimal('10000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'Teeth that share motion.',
    'image_path': '/media/objects/starter-gear.png'
    },
    {
    'object_name': 'Magnet',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'uncommon',
    'cost': Decimal('10000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'A lodestone with a pull on progress.',
    'image_path': '/media/objects/starter-magnet.png'
    },
    {
    'object_name': 'Shift Whistle',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'cultural',
    'quality_tier': 'uncommon',
    'cost': Decimal('80000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('700'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 180,
    'operation_duration_sec': 7200,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.5'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['factory', 'logistics'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 0.92,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'A piercing call snaps every line into motion on schedule.',
    'image_path': '/media/objects/starter-shiftwhistle.png'
    },
    {
    'object_name': 'Rail Milepost',
    'era_name': 'Steam & Industry',
    'is_keystone': False,
    'category': 'logistics',
    'quality_tier': 'uncommon',
    'cost': Decimal('90000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('750'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 200,
    'operation_duration_sec': 7500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.5'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['logistics'],
            'affected_tags': [],
            'income_multiplier': 1.08,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Perfectly spaced markers keep freight and passengers flowing.',
    'image_path': '/media/objects/starter-railpost.png'
    },
    # Electric Age starters
    {
    'object_name': 'Copper',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'common',
    'cost': Decimal('100000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'A bright path for electrons.',
    'image_path': '/media/objects/starter-copper.png'
    },
    {
    'object_name': 'Wire',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'logistics',
    'quality_tier': 'common',
    'cost': Decimal('100000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.3'),
    'global_modifiers': [],
    'flavor_text': 'A humble line that ties power together.',
    'image_path': '/media/objects/starter-wire.png'
    },
    {
    'object_name': 'Silicon',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'uncommon',
    'cost': Decimal('100000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.3'),
    'global_modifiers': [],
    'flavor_text': 'Sand made thoughtful.',
    'image_path': '/media/objects/starter-silicon.png'
    },
    {
    'object_name': 'Battery',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'common',
    'cost': Decimal('100000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Stored spark, ready on demand.',
    'image_path': '/media/objects/starter-battery.png'
    },
    {
    'object_name': 'Substation Signage',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'uncommon',
    'cost': Decimal('600000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('4000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 220,
    'operation_duration_sec': 9000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.6'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['power'],
            'affected_tags': [],
            'income_multiplier': 1.08,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Clear routing placards keep every circuit humming efficiently.',
    'image_path': '/media/objects/starter-substation.png'
    },
    {
    'object_name': 'Insulator Yard',
    'era_name': 'Electric Age',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('650000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('4200'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 240,
    'operation_duration_sec': 9500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.7'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['power'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.08,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Spools and ceramic racks stretch grid uptime between shutdowns.',
    'image_path': '/media/objects/starter-insulatoryard.png'
    },
    # Computing starters
    {
    'object_name': 'Circuit',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'factory',
    'quality_tier': 'common',
    'cost': Decimal('500000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Patterns that teach electrons to behave.',
    'image_path': '/media/objects/starter-circuit.png'
    },
    {
    'object_name': 'Code',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'common',
    'cost': Decimal('500000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.2'),
    'global_modifiers': [],
    'flavor_text': 'Instructions that organize thought.',
    'image_path': '/media/objects/starter-code.png'
    },
    {
    'object_name': 'Memory',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'uncommon',
    'cost': Decimal('500000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.3'),
    'global_modifiers': [],
    'flavor_text': 'Bits kept close for quick recall.',
    'image_path': '/media/objects/starter-memory.png'
    },
    {
    'object_name': 'Laser',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'uncommon',
    'cost': Decimal('500000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Light disciplined to a razor line.',
    'image_path': '/media/objects/starter-laser.png'
    },
    {
    'object_name': 'Cooling Stack',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('3500000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('22000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 260,
    'operation_duration_sec': 11000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.8'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['factory', 'research'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.10,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Heat sinks climb like towers, buying servers precious uptime.',
    'image_path': '/media/objects/starter-coolingstack.png'
    },
    {
    'object_name': 'Job Scheduler Board',
    'era_name': 'Computing',
    'is_keystone': False,
    'category': 'cultural',
    'quality_tier': 'uncommon',
    'cost': Decimal('3600000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('23000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 270,
    'operation_duration_sec': 11200,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.6'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['research'],
            'affected_tags': [],
            'income_multiplier': 1.07,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Color-coded queues keep every automation job cycling smoothly.',
    'image_path': '/media/objects/starter-schedulerboard.png'
    },
    # Futurism starters
    {
    'object_name': 'Superconductor',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'uncommon',
    'cost': Decimal('5000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Resistance falls to zero; dreams don’t.',
    'image_path': '/media/objects/starter-superconductor.png'
    },
    {
    'object_name': 'Assembler',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'factory',
    'quality_tier': 'common',
    'cost': Decimal('5000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.0'),
    'global_modifiers': [],
    'flavor_text': 'A small cell that builds bigger things.',
    'image_path': '/media/objects/starter-assembler.png'
    },
    {
    'object_name': 'Magnetic Coil',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'uncommon',
    'cost': Decimal('5000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.6'),
    'global_modifiers': [],
    'flavor_text': 'Field lines wound tight as springs.',
    'image_path': '/media/objects/starter-magneticcoil.png'
    },
    {
    'object_name': 'Energy Cell',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'common',
    'cost': Decimal('5000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'A pocket of captured lightning.',
    'image_path': '/media/objects/starter-energycell.png'
    },
    {
    'object_name': 'Polymer Ledger',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('20000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('130000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 320,
    'operation_duration_sec': 14000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.9'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['factory', 'power'],
            'affected_tags': [],
            'income_multiplier': 1.06,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Every batch run is logged, squeezing waste from high-tech fabs.',
    'image_path': '/media/objects/starter-polymerledger.png'
    },
    {
    'object_name': 'Composite Shielding',
    'era_name': 'Futurism',
    'is_keystone': False,
    'category': 'structure',
    'quality_tier': 'uncommon',
    'cost': Decimal('22000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('140000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 340,
    'operation_duration_sec': 14500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.0'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['factory'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.08,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Layered skins keep delicate fabrication lines running longer.',
    'image_path': '/media/objects/starter-compositeshield.png'
    },
    # Interstellar starters
    {
    'object_name': 'Orbital Telescope',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'uncommon',
    'cost': Decimal('50000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 2,
    'footprint_h': 2,
    'size': Decimal('1.2'),
    'global_modifiers': [],
    'flavor_text': 'Eyes above the sky.',
    'image_path': '/media/objects/starter-orbitaltelescope.png'
    },
    {
    'object_name': 'Quantum Lab',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'uncommon',
    'cost': Decimal('50000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 2,
    'footprint_h': 2,
    'size': Decimal('1.2'),
    'global_modifiers': [],
    'flavor_text': 'Where uncertainty becomes instrument.',
    'image_path': '/media/objects/starter-quantumlab.png'
    },
    {
    'object_name': 'Satellite Bus',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'logistics',
    'quality_tier': 'common',
    'cost': Decimal('50000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.8'),
    'global_modifiers': [],
    'flavor_text': 'The frame that carries spacefaring dreams.',
    'image_path': '/media/objects/starter-satellitebus.png'
    },
    {
    'object_name': 'Thruster',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'common',
    'cost': Decimal('50000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.9'),
    'global_modifiers': [],
    'flavor_text': 'Push enough, and the stars get closer.',
    'image_path': '/media/objects/starter-thruster.png'
    },
    {
    'object_name': 'Tracking Beacon',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'logistics',
    'quality_tier': 'uncommon',
    'cost': Decimal('150000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('900000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 420,
    'operation_duration_sec': 18000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.1'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['logistics', 'research'],
            'affected_tags': [],
            'income_multiplier': 1.08,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 3
        }
    ],
    'flavor_text': 'Relay chains whisper across the void, boosting every link in the network.',
    'image_path': '/media/objects/starter-trackingbeacon.png'
    },
    {
    'object_name': 'Waypoint Relay',
    'era_name': 'Interstellar',
    'is_keystone': False,
    'category': 'logistics',
    'quality_tier': 'uncommon',
    'cost': Decimal('160000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('920000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 440,
    'operation_duration_sec': 18500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.1'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['logistics'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 0.93,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Autonomous couriers pre-stage deliveries, trimming downtime between jumps.',
    'image_path': '/media/objects/starter-waypointrelay.png'
    },
    # Arcana starters
    {
    'object_name': 'Crystal',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'natural',
    'quality_tier': 'rare',
    'cost': Decimal('500000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.6'),
    'global_modifiers': [],
    'flavor_text': 'Facets hum with hidden hymns.',
    'image_path': '/media/objects/starter-crystal.png'
    },
    {
    'object_name': 'Mana',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'magic',
    'quality_tier': 'rare',
    'cost': Decimal('500000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.4'),
    'global_modifiers': [],
    'flavor_text': 'Raw current from the unseen.',
    'image_path': '/media/objects/starter-mana.png'
    },
    {
    'object_name': 'Rune',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'magic',
    'quality_tier': 'rare',
    'cost': Decimal('500000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.3'),
    'global_modifiers': [],
    'flavor_text': 'A small mark with a large voice.',
    'image_path': '/media/objects/starter-rune.png'
    },
    {
    'object_name': 'Chalk Circle',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'magic',
    'quality_tier': 'rare',
    'cost': Decimal('500000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.5'),
    'global_modifiers': [],
    'flavor_text': 'A boundary where rules may bend.',
    'image_path': '/media/objects/starter-chalkcircle.png'
    },
    {
    'object_name': 'Rune Circle',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'magic',
    'quality_tier': 'uncommon',
    'cost': Decimal('950000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('6000000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 460,
    'operation_duration_sec': 21000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.2'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['magic'],
            'affected_tags': [],
            'income_multiplier': 1.10,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Sigils flare bright, amplifying every working in its radius.',
    'image_path': '/media/objects/starter-runecircle.png'
    },
    {
    'object_name': 'Ley Tuning Fork',
    'era_name': 'Arcana',
    'is_keystone': False,
    'category': 'magic',
    'quality_tier': 'uncommon',
    'cost': Decimal('980000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('6200000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 480,
    'operation_duration_sec': 21500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.3'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['magic'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.10,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Struck once, it keeps ley pulses resonant far longer than they should be.',
    'image_path': '/media/objects/starter-leyfork.png'
    },
    # Beyond starters
    {
    'object_name': 'Archive Mirror',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'wonder',
    'quality_tier': 'uncommon',
    'cost': Decimal('7000000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('40000000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 520,
    'operation_duration_sec': 24000,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.5'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['research'],
            'affected_tags': [],
            'income_multiplier': 1.07,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.0,
            'stacking': 'multiplicative',
            'max_stacks': 2
        }
    ],
    'flavor_text': 'Parallel archives whisper answers forward, accelerating every breakthrough.',
    'image_path': '/media/objects/starter-archivemirror.png'
    },
    {
    'object_name': 'Convergence Anchor',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'wonder',
    'quality_tier': 'rare',
    'cost': Decimal('7200000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('41000000'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 540,
    'operation_duration_sec': 24500,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.15'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('2.6'),
    'global_modifiers': [
        {
            'active_when': 'operational',
            'affected_categories': ['natural', 'structure', 'farm', 'mine', 'factory', 'power', 'logistics', 'research', 'cultural', 'housing', 'magic'],
            'affected_tags': [],
            'income_multiplier': 1.0,
            'cost_multiplier': 1.0,
            'build_time_multiplier': 1.0,
            'operation_duration_multiplier': 1.10,
            'stacking': 'multiplicative',
            'max_stacks': 1
        }
    ],
    'flavor_text': 'Locks in reality so layouts run longer before the fabric frays.',
    'image_path': '/media/objects/starter-convergenceanchor.png'
    },
    {
    'object_name': 'Quantum Core',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'power',
    'quality_tier': 'epic',
    'cost': Decimal('5000000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.5'),
    'global_modifiers': [],
    'flavor_text': 'Computation condensed to a heartbeat.',
    'image_path': '/media/objects/starter-quantum.png'
    },
    {
    'object_name': 'Archive',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'epic',
    'cost': Decimal('5000000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.2'),
    'global_modifiers': [],
    'flavor_text': 'Memory made monument.',
    'image_path': '/media/objects/starter-archive.png'
    },
    {
    'object_name': 'Dataset',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'epic',
    'cost': Decimal('5000000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('0.8'),
    'global_modifiers': [],
    'flavor_text': 'Curated truths awaiting a mind.',
    'image_path': '/media/objects/starter-dataset.png'
    },
    {
    'object_name': 'Simulator',
    'era_name': 'Beyond',
    'is_keystone': False,
    'category': 'research',
    'quality_tier': 'epic',
    'cost': Decimal('5000000000'),
    'time_crystal_cost': Decimal('0'),
    'income_per_second': Decimal('0'),
    'time_crystal_generation': Decimal('0'),
    'build_time_sec': 0,
    'operation_duration_sec': 300,
    'retire_payout_coins_pct': Decimal('0.2'),
    'sellback_pct': Decimal('0.2'),
    'cap_per_civ': None,
    'footprint_w': 1,
    'footprint_h': 1,
    'size': Decimal('1.0'),
    'global_modifiers': [],
    'flavor_text': 'A sandbox for possible worlds.',
    'image_path': '/media/objects/starter-simulator.png'
    }
        ]

        for obj_data in starter_objects:
            # Add is_starter=True to the data
            obj_data['is_starter'] = True

            obj, created = GameObject.objects.get_or_create(
                object_name=obj_data['object_name'],
                defaults=obj_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created {obj.object_name}'))
            else:
                # Always update is_starter=True for existing objects
                if not obj.is_starter:
                    obj.is_starter = True
                    obj.save(update_fields=['is_starter'])
                    self.stdout.write(self.style.SUCCESS(f'Updated {obj.object_name} (marked as starter)'))
                else:
                    self.stdout.write(self.style.WARNING(f'{obj.object_name} already exists'))

        self.stdout.write(self.style.SUCCESS('Starter objects initialized!'))
