from django.core.management.base import BaseCommand
from game.models import GameObject
from decimal import Decimal


class Command(BaseCommand):
    help = 'Initialize starter objects for the game'

    def handle(self, *args, **kwargs):
        starter_objects = [
            # Hunter-Gatherer starters (already exist)
            {
                'object_name': 'Rock',
                'era_name': 'Hunter-Gatherer',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'A simple rock. Hard and useful.',
                'image_path': '/media/objects/starter-rock.png'
            },
            {
                'object_name': 'Stick',
                'era_name': 'Hunter-Gatherer',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'A sturdy stick. Nature\'s first tool.',
                'image_path': '/media/objects/starter-stick.png'
            },
            {
                'object_name': 'Water',
                'era_name': 'Hunter-Gatherer',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Pure water. Essential for life.',
                'image_path': '/media/objects/starter-water.png'
            },
            {
                'object_name': 'Dirt',
                'era_name': 'Hunter-Gatherer',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Rich earth. The foundation of all.',
                'image_path': '/media/objects/starter-dirt.png'
            },
            # Agriculture starters
            {
                'object_name': 'Seed',
                'era_name': 'Agriculture',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.3'),
                'global_modifiers': [],
                'flavor_text': 'A tiny seed with potential for growth.',
                'image_path': '/media/objects/starter-seed.png'
            },
            {
                'object_name': 'Clay',
                'era_name': 'Agriculture',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Moldable earth, foundation of pottery.',
                'image_path': '/media/objects/starter-clay.png'
            },
            {
                'object_name': 'Animal',
                'era_name': 'Agriculture',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.8'),
                'global_modifiers': [],
                'flavor_text': 'Domesticated livestock, provider of labor.',
                'image_path': '/media/objects/starter-animal.png'
            },
            {
                'object_name': 'Plant',
                'era_name': 'Agriculture',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.6'),
                'global_modifiers': [],
                'flavor_text': 'Cultivated vegetation, base of agriculture.',
                'image_path': '/media/objects/starter-plant.png'
            },
            # Metallurgy starters
            {
                'object_name': 'Ore',
                'era_name': 'Metallurgy',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('1000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.6'),
                'global_modifiers': [],
                'flavor_text': 'Raw metal ore, waiting to be refined.',
                'image_path': '/media/objects/starter-ore.png'
            },
            {
                'object_name': 'Coal',
                'era_name': 'Metallurgy',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('1000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Black fuel for intense heat.',
                'image_path': '/media/objects/starter-coal.png'
            },
            {
                'object_name': 'Fire',
                'era_name': 'Metallurgy',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('1000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.7'),
                'global_modifiers': [],
                'flavor_text': 'Controlled flame for smelting and forging.',
                'image_path': '/media/objects/starter-fire.png'
            },
            {
                'object_name': 'Stone',
                'era_name': 'Metallurgy',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('1000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.6'),
                'global_modifiers': [],
                'flavor_text': 'Quarried stone for foundational structures.',
                'image_path': '/media/objects/starter-stone.png'
            },
            # Steam & Industry starters
            {
                'object_name': 'Iron',
                'era_name': 'Steam & Industry',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.7'),
                'global_modifiers': [],
                'flavor_text': 'Refined iron, backbone of industry.',
                'image_path': '/media/objects/starter-iron.png'
            },
            {
                'object_name': 'Steam',
                'era_name': 'Steam & Industry',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('10000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.8'),
                'global_modifiers': [],
                'flavor_text': 'Harnessed water vapor, power of revolution.',
                'image_path': '/media/objects/starter-steam.png'
            },
            {
                'object_name': 'Steel',
                'era_name': 'Steam & Industry',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('10000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.7'),
                'global_modifiers': [],
                'flavor_text': 'Strong alloy of iron and carbon.',
                'image_path': '/media/objects/starter-steel.png'
            },
            {
                'object_name': 'Gear',
                'era_name': 'Steam & Industry',
                'is_keystone': False,
                'category': 'factory',
                'quality_tier': 'common',
                'cost': Decimal('10000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Mechanical component for transmitting power.',
                'image_path': '/media/objects/starter-gear.png'
            },
            # Electric Age starters
            {
                'object_name': 'Copper',
                'era_name': 'Electric Age',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Conductive metal for electrical systems.',
                'image_path': '/media/objects/starter-copper.png'
            },
            {
                'object_name': 'Magnet',
                'era_name': 'Electric Age',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('100000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Mysterious force that attracts and repels.',
                'image_path': '/media/objects/starter-magnet.png'
            },
            {
                'object_name': 'Wire',
                'era_name': 'Electric Age',
                'is_keystone': False,
                'category': 'logistics',
                'quality_tier': 'common',
                'cost': Decimal('100000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.3'),
                'global_modifiers': [],
                'flavor_text': 'Conductor for electrical transmission.',
                'image_path': '/media/objects/starter-wire.png'
            },
            {
                'object_name': 'Glass',
                'era_name': 'Electric Age',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('100000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Transparent material for insulators and bulbs.',
                'image_path': '/media/objects/starter-glass.png'
            },
            # Computing starters
            {
                'object_name': 'Silicon',
                'era_name': 'Computing',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('500000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.3'),
                'global_modifiers': [],
                'flavor_text': 'Foundation of the digital age.',
                'image_path': '/media/objects/starter-silicon.png'
            },
            {
                'object_name': 'Circuit',
                'era_name': 'Computing',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('500000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Electronic pathways for data flow.',
                'image_path': '/media/objects/starter-circuit.png'
            },
            {
                'object_name': 'Data',
                'era_name': 'Computing',
                'is_keystone': False,
                'category': 'research',
                'quality_tier': 'common',
                'cost': Decimal('500000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.2'),
                'global_modifiers': [],
                'flavor_text': 'Information stored in binary form.',
                'image_path': '/media/objects/starter-data.png'
            },
            {
                'object_name': 'Code',
                'era_name': 'Computing',
                'is_keystone': False,
                'category': 'research',
                'quality_tier': 'common',
                'cost': Decimal('500000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.2'),
                'global_modifiers': [],
                'flavor_text': 'Instructions that make machines think.',
                'image_path': '/media/objects/starter-code.png'
            },
            # Futurism starters
            {
                'object_name': 'Polymer',
                'era_name': 'Futurism',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'common',
                'cost': Decimal('5000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Advanced synthetic material.',
                'image_path': '/media/objects/starter-polymer.png'
            },
            {
                'object_name': 'Assembler',
                'era_name': 'Futurism',
                'is_keystone': False,
                'category': 'factory',
                'quality_tier': 'common',
                'cost': Decimal('5000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.0'),
                'global_modifiers': [],
                'flavor_text': 'Automated construction unit.',
                'image_path': '/media/objects/starter-assembler.png'
            },
            {
                'object_name': 'Nanites',
                'era_name': 'Futurism',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'uncommon',
                'cost': Decimal('5000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.3'),
                'global_modifiers': [],
                'flavor_text': 'Microscopic machines that build at atomic scale.',
                'image_path': '/media/objects/starter-nanites.png'
            },
            {
                'object_name': 'Energy Cell',
                'era_name': 'Futurism',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('5000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Compact energy storage for advanced tech.',
                'image_path': '/media/objects/starter-energycell.png'
            },
            # Interstellar starters
            {
                'object_name': 'Fusion',
                'era_name': 'Interstellar',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'common',
                'cost': Decimal('50000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.2'),
                'global_modifiers': [],
                'flavor_text': 'Star power contained.',
                'image_path': '/media/objects/starter-fusion.png'
            },
            {
                'object_name': 'Exotic Matter',
                'era_name': 'Interstellar',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'uncommon',
                'cost': Decimal('50000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Strange substance from beyond our world.',
                'image_path': '/media/objects/starter-exotic.png'
            },
            {
                'object_name': 'Antimatter',
                'era_name': 'Interstellar',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'rare',
                'cost': Decimal('50000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Matter\'s opposite, incredibly powerful.',
                'image_path': '/media/objects/starter-antimatter.png'
            },
            {
                'object_name': 'Void Essence',
                'era_name': 'Interstellar',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'rare',
                'cost': Decimal('50000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.5'),
                'global_modifiers': [],
                'flavor_text': 'Harvested from the void between stars.',
                'image_path': '/media/objects/starter-voidessence.png'
            },
            # Arcana starters
            {
                'object_name': 'Crystal',
                'era_name': 'Arcana',
                'is_keystone': False,
                'category': 'natural',
                'quality_tier': 'rare',
                'cost': Decimal('500000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.6'),
                'global_modifiers': [],
                'flavor_text': 'Magical crystal resonating with power.',
                'image_path': '/media/objects/starter-crystal.png'
            },
            {
                'object_name': 'Ritual',
                'era_name': 'Arcana',
                'is_keystone': False,
                'category': 'magic',
                'quality_tier': 'rare',
                'cost': Decimal('500000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.0'),
                'global_modifiers': [],
                'flavor_text': 'Ancient ceremony channeling mystic forces.',
                'image_path': '/media/objects/starter-ritual.png'
            },
            {
                'object_name': 'Mana',
                'era_name': 'Arcana',
                'is_keystone': False,
                'category': 'magic',
                'quality_tier': 'rare',
                'cost': Decimal('500000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.4'),
                'global_modifiers': [],
                'flavor_text': 'Raw magical energy from the ether.',
                'image_path': '/media/objects/starter-mana.png'
            },
            {
                'object_name': 'Rune',
                'era_name': 'Arcana',
                'is_keystone': False,
                'category': 'magic',
                'quality_tier': 'rare',
                'cost': Decimal('500000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.3'),
                'global_modifiers': [],
                'flavor_text': 'Symbol of power inscribed with magic.',
                'image_path': '/media/objects/starter-rune.png'
            },
            # Beyond starters
            {
                'object_name': 'Quantum Core',
                'era_name': 'Beyond',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'epic',
                'cost': Decimal('5000000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.5'),
                'global_modifiers': [],
                'flavor_text': 'Computing beyond comprehension.',
                'image_path': '/media/objects/starter-quantum.png'
            },
            {
                'object_name': 'Archive',
                'era_name': 'Beyond',
                'is_keystone': False,
                'category': 'research',
                'quality_tier': 'epic',
                'cost': Decimal('5000000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.2'),
                'global_modifiers': [],
                'flavor_text': 'Repository of all knowledge ever recorded.',
                'image_path': '/media/objects/starter-archive.png'
            },
            {
                'object_name': 'Singularity',
                'era_name': 'Beyond',
                'is_keystone': False,
                'category': 'power',
                'quality_tier': 'legendary',
                'cost': Decimal('5000000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('1.0'),
                'global_modifiers': [],
                'flavor_text': 'A point of infinite density and possibility.',
                'image_path': '/media/objects/starter-singularity.png'
            },
            {
                'object_name': 'Paradox',
                'era_name': 'Beyond',
                'is_keystone': False,
                'category': 'magic',
                'quality_tier': 'legendary',
                'cost': Decimal('5000000000'),
                'time_crystal_cost': Decimal('0'),
                'income_per_second': Decimal('0'),
                'time_crystal_generation': Decimal('0'),
                'build_time_sec': 0,
                'operation_duration_sec': 300,
                'retire_payout_coins_pct': Decimal('0.2'),
                'sellback_pct': Decimal('0.2'),
                'cap_per_civ': None,
                'footprint_w': 1,
                'footprint_h': 1,
                'size': Decimal('0.8'),
                'global_modifiers': [],
                'flavor_text': 'Logic breaks down. Impossibility made real.',
                'image_path': '/media/objects/starter-paradox.png'
            }
        ]

        for obj_data in starter_objects:
            obj, created = GameObject.objects.get_or_create(
                object_name=obj_data['object_name'],
                defaults=obj_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created {obj.object_name}'))
            else:
                self.stdout.write(self.style.WARNING(f'{obj.object_name} already exists'))

        self.stdout.write(self.style.SUCCESS('Starter objects initialized!'))
